### ISSUE TITLE
feed factory is passing incorrect address

### ISSUE THREAD

**Issue by thegostep** [ankitchiplunkar/erasure.py#10]
https://github.com/ankitchiplunkar/erasure.py/blob/71456dbaa848af1013c7d09fb9e468a20d626f81/erasure/erasure_client.py#L58

this should be an optional operator (I recommend default to null address)

**Comment by ankitchiplunkar** [comment]
Have resolved with this PR: https://github.com/ankitchiplunkar/erasure.py/pull/18
