### ISSUE TITLE
add support for deployment to local test env

### ISSUE THREAD

**Issue by thegostep** [ankitchiplunkar/erasure.py#13]
https://github.com/ankitchiplunkar/erasure.py/blob/71456dbaa848af1013c7d09fb9e468a20d626f81/erasure/erasure_client.py#L32

**Comment by ankitchiplunkar** [comment]
have resolved the issue in this PR: https://github.com/ankitchiplunkar/erasure.py/pull/14
docs here: https://github.com/ankitchiplunkar/erasure.py#testing
